/**
 * Automatically generated by tongoose
 *
 * Check out the project at
 * https://github.com/tongoose/tongoose
 * 
 * Copyright (c) 2019 Kipras Melnikovas <kipras@kipras.org>
 * MIT Licensed
 */

/** @tongoose: formatted using `prettier` with options {"parser":"typescript"} */

import { ObjectId, Decimal128 } from "bson"; // `npm i --save-dev @types/mongodb`

export interface IUser {
  username?: string;
  email: string;
  password: string;
}
